import type { CommitInfo } from '../git/gitDiff.js';

export type AnalyzeFlags = {
  from?: string;
  to?: string;
  messageFilter?: string;
  model?: string;
};

type OpenAiClient = {
  chat: {
    completions: {
      create(...options: unknown[]): Promise<unknown>;
    };
  };
};

type OpenAiClientProvider = () => Promise<OpenAiClient>;

export async function generateSummary(
  diffText: string,
  fileNames: string[],
  commits: CommitInfo[],
  flags: AnalyzeFlags,
  openAiClientProvider?: OpenAiClientProvider
): Promise<string> {
  const fileSection = fileNames.length
    ? fileNames.map((name) => `- ${name}`).join('\n')
    : '- No metadata files changed.';

  const prompt = `Summarize Salesforce metadata changes between ${flags.from ?? 'HEAD~1'} and ${flags.to ?? 'HEAD'}.

Changed files:\n${fileNames.join('\n') || 'None'}\n
Commit messages:\n${commits.map((commit) => `- ${commit.hash.slice(0, 7)} ${commit.message}`).join('\n')}

Diff:\n${diffText}`;

  if (process.env.OPENAI_API_KEY) {
    return callOpenAi(
      prompt,
      flags.model ?? 'gpt-4o-mini',
      openAiClientProvider ??
        /* istanbul ignore next */ (async (): Promise<OpenAiClient> => {
          const { default: OpenAI } = await import('openai');
          return new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
        })
    );
  }

  return buildFallbackSummary(fileSection, commits, diffText, flags);
}

function buildFallbackSummary(
  fileSection: string,
  commits: CommitInfo[],
  diffText: string,
  flags: AnalyzeFlags
): string {
  const filterText = flags.messageFilter
    ? `Filtered by: \`${flags.messageFilter}\`\n\n`
    : 'No commit message filter applied.\n\n';

  return (
    '# Metadata Change Summary\n\n' +
    '## Range\n' +
    `From: ${flags.from ?? 'HEAD~1'}\n` +
    `To: ${flags.to ?? 'HEAD'}\n\n` +
    '## Commit Filter\n' +
    filterText +
    `## Changed Files\n${fileSection}\n\n` +
    '## Local Summary\n' +
    'This plugin could not find an OPENAI_API_KEY, so it generated a local summary instead.\n\n' +
    '### Commits\n' +
    commits.map((commit) => `- ${commit.hash.slice(0, 7)} ${commit.message}`).join('\n') +
    `\n\n### Diff Snippet\n\n${diffText.substring(0, 10_000)}`
  );
}

async function callOpenAi(prompt: string, model: string, openAiClientProvider: OpenAiClientProvider): Promise<string> {
  const client = await openAiClientProvider();
  const response = await client.chat.completions.create({
    model,
    messages: [
      {
        role: 'system',
        content: 'You are an AI assistant that summarizes Salesforce metadata changes from git diff output.',
      },
      {
        role: 'user',
        content: prompt,
      },
    ],
    temperature: 0.2,
    max_tokens: 1000,
  });

  const typedResponse = response as {
    choices?: Array<{ message?: { content?: string } }>;
  };

  return typedResponse.choices?.[0]?.message?.content?.trim() ?? 'No summary generated by OpenAI.';
}
